### ISSUE TITLE
Example with chinese cheap spy camera

### ISSUE THREAD

**Issue by ipald** [fbertone/lib32100#2]
Ciao!
Mi sono imbattuto casualmente nel tuo progetto e l'ho trovato molto interessante. Solo non capisco su quale categorie di prodotti cinesi dovrebbe applicarsi.
Ho recentemente acquistato una spy-camera cinese economica (https://www.banggood.com/it/DANIU-Mini-Wireless-Hidden-Camera-WIFI-IP-Pinhole-DIY-P2P-Video-Camera-Support-TF-Card-Audio-p-1146803.html?cur_warehouse=CN) e ho fatto varie prove con la tua libreria ma non sono riuscito a utilizzarla... secondo te è possibile? Come posso verificarlo?
Grazie, a presto!

**Comment by fbertone** [comment]
Ciao,
no direi che non e' compatibile, il formato dell'ID e' differente
